services:
    jekyll:
      build: .
      volumes:
        - .:/srv/jekyll:Z
        - ./vendor/bundle:/usr/local/bundle:Z
      ports:
        - "4000:4000"
      command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --incremental"